# Generated by Django 6.0.5 on 2026-06-01 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicalrecord',
            old_name='aplication_date',
            new_name='application_date',
        ),
    ]
